title: 作家の手帖
description: >-
  じぶんの「つづき」を書こう。

repository: 'Writer-Life-Committee/authors-note'

baseurl: '/authors-note'

defaults:
  - scope:
      path: ""
    values:
      image:
        path: /assets/images/main.jpeg
        height: 630
        width: 1200

locale: 'ja_JP'
timezone: 'Asia/Tokyo'

show_downloads: false

theme: jekyll-theme-merlot

plugins:
  - jekyll-sitemap
  - github-pages

sass:
  style: compressed
